name: Merge Into Main

on:
  push:
    branches:
      - develop
jobs:
    merge-branch:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              token: ${{ secrets.PAT }}
    
          - name: Merge to main
            run: |
                git config user.name "Update branch"
                git config user.email github-actions@github.com
                git merge main --no-edit -m "Merged main branch on $(date +%F)"
       