name: Merge Into Main

on:
  push:
    branches:
      - develop

env:
 DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
    merge-branch:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0   
              token: ${{ secrets.PAT }}
    
          - name: Merge to main
            run: |
                git config --global user.email "${GITHUB_ACTOR}"
                git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
                git status
                git pull
                git checkout "$DEFAULT_BRANCH"
                git status
                git pull
                git checkout "$GITHUB_HEAD_REF"
                git merge "$DEFAULT_BRANCH" --no-edit
                git push
                git status
       