name: Merge Into Main

on:
  push:
    branches:
      - develop

env:
 DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
    merge-branch:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0   
              token: ${{ secrets.PAT }}